name: Create source (daily job)

on:
  schedule:
    - cron: "30 0,12 * * *"
  push:
    branches:
      - main
    paths:
      - 'sources/**'
      - 'res/**/*{.png,.jpg,.jpeg,.html}'
      - 'requirements.txt'
      - '.github/workflows/*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-source:
    name: Create sources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set current date
        run: echo "DATE=$(date --rfc-3339=date)" >> $GITHUB_ENV
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Generate the osu! source
        run: python sources/osu.py || true

      # - name: Generate the Sonolus source
      #  run: python sources/sonolus.py

      - name: Commit updated sources to 'main' branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Source creation (${{ env.DATE }})
          file_pattern: res/**/index.json
          commit_user_name: apixbot (GHA // @apikusu/altstore)
          commit_user_email: 228819170+apixbot@users.noreply.github.com
          commit_author: "apixbot (GHA // @apikusu/altstore) <228819170+apixbot@users.noreply.github.com>"
