name: Create source (daily job)
on:
    schedule:
        - cron: "30 4 * * *"
    push:
        branches:
            - main

permissions:
    pages: write
    id-token: write

jobs:
    create-source:
        name: Generate Repository
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Generate the source
              run: python generate-source.py

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v1
              with:
                  path: ./res

    deploy:
        name: Deploy source to GitHub Pages
        needs: create-source
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write
        steps:
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v1