name: Create source (daily job)
on:
    schedule:
        - cron: "30 4 * * *"
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    create-source:
        name: Generate Repository
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v1

            - name: Generate the osu! source
              run: python sources/osu.py

            - name: Generate the Sonolus source
              run: python sources/sonolus.py

            - name: Upload GitHub Pages artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: ./res

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        name: Deploy source to GitHub Pages
        needs: create-source
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4