name: Deploy to GitHub Pages

on:
  push:
    paths:
      - 'res/**'

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy sources to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./res

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
